version: "3"
   
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - lucia-mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'lucia_education'
      MYSQL_ROOT_PASSWORD: 'secret'
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - '8080:80'
    depends_on:
        - db
  
  web:
    build: .
    command: sh -c "./manage.py migrate && gunicorn emis.wsgi -b 0.0.0.0:8000"
    working_dir: /application
    volumes:
      - .:/application
    ports:
      - '8000:8000'
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: lucia_education
    depends_on:
      - db

volumes:
   lucia-mysql-data: