version: "3"
   
services:
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    volumes:
      - lucia-mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'lucia_education'
      MYSQL_ROOT_PASSWORD: 'secret'

  web:
    build: .
    command: sh -c "./manage.py migrate && gunicorn emis.wsgi -b 0.0.0.0:8000"
    working_dir: /application
    volumes:
      - .:/application
    ports:
      - "80:8000"
      - "443:8000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: lucia_education
    depends_on:
      - db

volumes:
   lucia-mysql-data: