# Generated by Django 3.1.7 on 2021-04-28 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0002_auto_20210427_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsupportassoc',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='studentsupportassoc',
            old_name='start',
            new_name='start_date',
        ),
    ]
