# Generated by Django 3.1.7 on 2021-04-28 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0003_auto_20210428_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsupportassoc',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='studentsupportassoc',
            name='start_date',
            field=models.DateField(default=datetime.date.today, max_length=8),
        ),
    ]
