# Generated by Django 3.1.7 on 2021-05-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseoutcome',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='teacherappraisal',
            options={'default_permissions': ()},
        ),
    ]
