# Generated by Django 3.1.7 on 2021-05-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='device_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_device_personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='steady_internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='type_of_device',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('tablet', 'Tablet'), ('laptop/computer', 'Laptop / Computer')], max_length=30, null=True),
        ),
    ]
