# Generated by Django 3.1.7 on 2021-05-02 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('days_absent', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
            options={
                'unique_together': {('course', 'student')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='assignmentgrade',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='assignmentgrade',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentgrade',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='coursegrade',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coursegrade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursegrade',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentGrade',
        ),
        migrations.DeleteModel(
            name='CourseGrade',
        ),
    ]
