# Generated by Django 3.1.7 on 2021-05-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210510_1553'),
        ('school', '0002_auto_20210510_2035'),
    ]

    operations = [
    ]
