# Generated by Django 3.1.7 on 2021-04-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historical_surveillance', '0005_populate_schools'),
        ('school', '0002_auto_20210421_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_school_attended',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_school', to='historical_surveillance.school'),
        ),
    ]
