# Generated by Django 3.1.7 on 2021-05-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210502_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoutcome',
            name='notes',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
