# Generated by Django 3.1.7 on 2021-04-21 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210421_2144'),
        ('school', '0003_auto_20210421_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PrincipalAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_experience_years', models.IntegerField()),
                ('teaching_staff', models.IntegerField()),
                ('ancillary_staff', models.IntegerField()),
                ('administrative_staff', models.IntegerField()),
                ('evaluation_period_start', models.DateField(max_length=8)),
                ('evaluation_period_end', models.DateField(max_length=8)),
                ('last_appraisal', models.DateField(max_length=8)),
                ('pre_conference', models.BooleanField(default=False)),
                ('class_visits', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('class_observation', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('teacher_reviews', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('conducts_lessons', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('ensures_literacy_improvement', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('student_achivevemnet', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('class_supervision', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('school_development_plan', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('smart_objectives', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('annual_work_plan', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('submits_to_ministry', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('plan_implementation', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('master_time_table', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('time_table_available', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('ensure_teacher_comply_time_table', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('prepare_annual_report', models.IntegerField(choices=[(5, '(A)'), (4, '(VO)'), (3, '(O)'), (2, '(SO)'), (1, '(SE)'), (0, '(N)')])),
                ('principals_comments', models.CharField(max_length=1024)),
                ('district_education_officer_comments', models.CharField(max_length=1024)),
                ('chief_education_officer_comments', models.CharField(max_length=1024)),
                ('principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.schoolprincipal')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'year')},
            },
        ),
    ]
