# Generated by Django 3.1.7 on 2021-04-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210409_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='graduation_year',
            field=models.PositiveIntegerField(default=2021),
        ),
    ]
