# Generated by Django 3.1.7 on 2021-04-02 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictAdministration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('create_principal_appraisal', 'Can create principal appraisals'), ('update_principal_appraisal', 'Can update principal appraisals'), ('view_principal_appraisal', 'Can view principal appraisals')],
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EarlyChildhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [],
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EvaluationAndAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('create_accommodation_enrollment', 'Can create accommodation enrollments'), ('update_accommodation_enrollment', 'Can update accommodation enrollments'), ('view_accommodation_enrollment', 'Can view accommodation enrollments')],
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ExternalAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('create_external_assessment', 'Can create external assessment report forms'), ('update_external_assessment', 'Can update external assessment report forms'), ('view_external_assessment', 'Can view external assessment report forms')],
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('create_teacher_appraisal', 'Can create teacher appraisals'), ('update_teacher_appraisal', 'Can update teacher appraisals'), ('view_teacher_appraisal', 'Can view teacher appraisals'), ('create_vice_principal_appraisal', 'Can create vice principal appraisals'), ('update_vice_principal_appraisal', 'Can update vice principal appraisals'), ('view_vice_principal_appraisal', 'Can view vice principal appraisals')],
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RestrictedSchoolAdministration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('create_teacher_enrollment', 'Can create teacher enrollment'), ('update_teacher_enrollment', 'Can update teacher enrollment'), ('view_teacher_enrollment', 'Can view teacher enrollment')],
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SchoolAdministration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('create_accounting', 'Can create accounting and budgeting information'), ('update_accounting', 'Can update accounting and budgeting information'), ('view_accounting', 'Can view accounting and budgeting information'), ('create_school_activity_config', 'Can create school subjects, cocurricular, and extra-curricular activities'), ('update_school_activity_config', 'Can update school subjects, cocurricular, and extra-curricular activities'), ('view_school_activity_config', 'Can view school subjects, cocurricular, and extra-curricular activities'), ('create_student_enrollment', 'Can create student enrollment'), ('update_student_enrollment', 'Can update student enrollment'), ('view_student_enrollment', 'Can view student enrollment'), ('create_student_transfer', 'Can create student transfers'), ('update_student_transfer', 'Can update student transfers'), ('view_student_transfer', 'Can view student transfers')],
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SchoolSupervision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('create_supervision_report', 'Can create school supervision reports'), ('update_supervision_report', 'Can update school supervision reports'), ('view_supervision_report', 'Can view school supervision reports')],
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StatisticsAndPlanning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('create_stats_report', 'Can create aggregated data / statistical planning reports'), ('update_stats_report', 'Can update aggregated data / statistical planning reports'), ('view_stats_report', 'Can view aggregated data / statistical planning reports'), ('create_stats_data_management', 'Can create statistical data'), ('update_stats_data_management', 'Can update statistical data'), ('view_stats_data_management', 'Can view statistical data')],
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SupportServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('create_student_support_form', 'Can create student support forms'), ('update_student_support_form', 'Can update student support forms'), ('view_student_support_form', 'Can view student support forms'), ('create_student_resource_form', 'Can create student resource allocation forms'), ('update_student_resource_form', 'Can update student resource allocation forms'), ('view_student_resource_form', 'Can view student resource allocation forms'), ('create_student_counsel_forms', 'Can create student counseling forms'), ('update_student_counsel_forms', 'Can update student counseling forms'), ('view_student_counsel_forms', 'Can view student counseling forms')],
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('create_student_attendance', 'Can create student attendance'), ('update_student_attendance', 'Can update student attendance'), ('view_student_attendance', 'Can view student attendance'), ('create_student_grades', 'Can create student grades'), ('update_student_grades', 'Can update student grades'), ('view_student_grades', 'Can view student grades'), ('create_student_dev_behavioral', 'Can create student developmental and behavioral data'), ('update_student_dev_behavioral', 'Can update student developmental and behavioral data'), ('view_student_dev_behavioral', 'Can view student developmental and behavioral data')],
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('code', models.CharField(max_length=50)),
            ],
        ),
    ]
