# Generated by Django 3.1.7 on 2021-05-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_group_migrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolsupervisionofficer',
            options={'default_permissions': (), 'verbose_name': 'School Supervision Officer'},
        ),
        migrations.RemoveField(
            model_name='schoolsupervisionofficer',
            name='school',
        ),
    ]
