# Generated by Django 3.1.7 on 2021-04-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historical_surveillance', '0004_auto_20210421_2330'),
        ('authentication', '0003_auto_20210421_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlychildhoodeducator',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='historical_surveillance.school'),
        ),
        migrations.AddField(
            model_name='schoolsuperviser',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='historical_surveillance.school'),
        ),
    ]
