# Generated by Django 3.1.7 on 2021-05-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210510_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earlychildhoodeducationofficer',
            name='school',
        ),
    ]
