# Generated by Django 3.1.7 on 2021-04-20 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210419_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_school_app', 'Can view school application'), ('view_welfare_app', 'Can view welfare and supervision application'), ('view_surveillance_app', 'Can view historical surveillance application')]},
        ),
    ]
