# Generated by Django 3.1.7 on 2021-04-27 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210424_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportservices',
            options={'default_permissions': (), 'managed': False, 'permissions': [('create_student_support_definition', 'Can create student support/service definitions'), ('update_student_support_definition', 'Can update student support/service definitions'), ('view_student_support_definition', 'Can view student support/service definitions'), ('create_student_resource_alloc', 'Can create student support/service allocations'), ('update_student_resource_alloc', 'Can update student support/service allocations'), ('view_student_resource_alloc', 'Can view student support/service allocations'), ('create_student_counsel_forms', 'Can create student counseling forms'), ('update_student_counsel_forms', 'Can update student counseling forms'), ('view_student_counsel_forms', 'Can view student counseling forms')]},
        ),
    ]
