# Generated by Django 3.1.7 on 2021-03-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('name_of_school', models.CharField(max_length=55)),
                ('academic_year', models.CharField(max_length=20)),
                ('category_of_school', models.CharField(choices=[('primary school', 'Primary School'), ('secondary school', 'Secondary School'), ('other', 'Other')], max_length=20)),
                ('district_of_school', models.CharField(choices=[('district 1', 'District 1'), ('district 2', 'District 2'), ('district 3', 'District 3'), ('district 4', 'District 4'), ('district 5', 'District 5'), ('district 6', 'District 6'), ('district 7', 'District 7'), ('district 8', 'District 8')], max_length=20)),
                ('capacity_of_school', models.IntegerField()),
                ('total_enrollment', models.IntegerField()),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('District_Code', models.CharField(blank=True, max_length=50)),
                ('District_Name', models.CharField(choices=[('district 1', 'District 1'), ('district 2', 'District 2'), ('district 3', 'District 3'), ('district 4', 'District 4'), ('district 5', 'District 5'), ('district 6', 'District 6'), ('district 7', 'District 7'), ('district 8', 'District 8')], max_length=50)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('category_of_school', models.CharField(choices=[('primary school', 'Primary School'), ('secondary school', 'Secondary School'), ('other', 'Other')], default=None, max_length=20)),
                ('district', models.CharField(choices=[('district 1', 'District 1'), ('district 2', 'District 2'), ('district 3', 'District 3'), ('district 4', 'District 4'), ('district 5', 'District 5'), ('district 6', 'District 6'), ('district 7', 'District 7'), ('district 8', 'District 8')], default='Select', max_length=20)),
                ('grade', models.CharField(choices=[('grade k', 'Grade k'), ('grade 1', 'Grade 1'), ('grade 2', 'Grade 2'), ('grade 3', 'Grade 3'), ('grade 4', 'Grade 4'), ('grade 5', 'Grade 5'), ('grade 6', 'Grade 6'), ('form 1', 'Form 1'), ('form 2', 'Form 2'), ('form 3', 'Form 3'), ('form 4', 'Form 4'), ('form 5', 'Form 5')], default=None, max_length=20)),
                ('enrollment', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('School_Code', models.CharField(blank=True, max_length=50)),
                ('School_Name', models.CharField(max_length=50)),
                ('District_Name', models.CharField(choices=[('district 1', 'District 1'), ('district 2', 'District 2'), ('district 3', 'District 3'), ('district 4', 'District 4'), ('district 5', 'District 5'), ('district 6', 'District 6'), ('district 7', 'District 7'), ('district 8', 'District 8')], max_length=20)),
                ('category_of_school', models.CharField(choices=[('primary school', 'Primary School'), ('secondary school', 'Secondary School'), ('other', 'Other')], max_length=20)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
