# Generated by Django 3.1.7 on 2021-04-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=255)),
                ("district_code", models.CharField(blank=True, max_length=50)),
                ("district_name", models.CharField(max_length=50)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=255)),
                ("school_code", models.CharField(blank=True, max_length=50)),
                ("school_name", models.CharField(max_length=50)),
                (
                    "category_of_school",
                    models.CharField(
                        choices=[
                            ("public primary", "Public Primary"),
                            ("public secondary", "Public Secondary"),
                            ("private primary", "Private Primary"),
                            ("private secondary", "Private Secondary"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=255)),
                (
                    "district_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="historical_surveillance.district",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=255)),
                ("year", models.CharField(max_length=20)),
                (
                    "category_of_school",
                    models.CharField(
                        choices=[
                            ("public primary", "Public Primary"),
                            ("public secondary", "Public Secondary"),
                            ("private primary", "Private Primary"),
                            ("private secondary", "Private Secondary"),
                            ("other", "Other"),
                        ],
                        default=None,
                        max_length=50,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("grade k", "Grade k"),
                            ("grade 1", "Grade 1"),
                            ("grade 2", "Grade 2"),
                            ("grade 3", "Grade 3"),
                            ("grade 4", "Grade 4"),
                            ("grade 5", "Grade 5"),
                            ("grade 6", "Grade 6"),
                            ("form 1", "Form 1"),
                            ("form 2", "Form 2"),
                            ("form 3", "Form 3"),
                            ("form 4", "Form 4"),
                            ("form 5", "Form 5"),
                            ("form 6 L1", "Form 6 L1"),
                            ("form 6 L2", "Form 6 L2"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("enrollment", models.IntegerField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("updated_by", models.CharField(max_length=255)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="historical_surveillance.district",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="historical_surveillance.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AggregateEnrollment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=255)),
                ("academic_year", models.CharField(max_length=20)),
                (
                    "category_of_school",
                    models.CharField(
                        choices=[
                            ("public primary", "Public Primary"),
                            ("public secondary", "Public Secondary"),
                            ("private primary", "Private Primary"),
                            ("private secondary", "Private Secondary"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("capacity_of_school", models.IntegerField()),
                ("total_enrollment", models.IntegerField()),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("updated_by", models.CharField(max_length=255)),
                (
                    "district_of_school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="historical_surveillance.district",
                    ),
                ),
                (
                    "name_of_school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="historical_surveillance.school",
                    ),
                ),
            ],
        ),
    ]
