# Generated by Django 3.1.7 on 2021-05-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_surveillance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
