# Generated by Django 3.1.7 on 2021-05-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_surveillance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CEEResults',
        ),
        migrations.DeleteModel(
            name='CSECResults',
        ),
        migrations.AlterField(
            model_name='cee',
            name='test_yr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
