# Generated by Django 3.1.7 on 2021-05-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_surveillance', '0002_auto_20210506_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cee',
            name='test_yr',
            field=models.IntegerField(null=True),
        ),
    ]
