# Generated by Django 3.1.7 on 2021-05-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historical_surveillance', '0002_ceeresults_csecresults_primaryperformance'),
        ('historical_surveillance', '0002_auto_20210501_0159'),
    ]

    operations = [
    ]
