# Generated by Django 3.1.7 on 2021-05-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historical_surveillance', '0002_auto_20210505_0851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CEEResults',
        ),
        migrations.DeleteModel(
            name='CSECResults',
        ),
    ]
