# Generated by Django 3.1.7 on 2021-05-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_surveillance', '0003_auto_20210506_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryperformance',
            name='feeding_program',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='primaryperformance',
            name='girls',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='primaryperformance',
            name='primary_enrollment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='primaryperformance',
            name='repeaters',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='primaryperformance',
            name='teachers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='primaryperformance',
            name='total_bursaries',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='primaryperformance',
            name='trained_teachers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='primaryperformance',
            name='above_average_scores',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='primaryperformance',
            name='tests_sat',
            field=models.IntegerField(null=True),
        ),
    ]
