# Generated by Django 3.1.7 on 2021-04-21 19:03

import logging
import csv

from django.db import models, migrations
from django.core.management.sql import emit_post_migrate_signal

from emis.groups import build_groups
from historical_surveillance.models import District, School

LOGGER = logging.getLogger(__name__)


def populate_school(apps, schema_editor):
    """
    PRS 22-Mar 2021: some helpful resources discussing this approach...

    https://stackoverflow.com/questions/25024795/django-1-7-where-to-put-the-code-to-add-groups-programmatically/25803284
    https://stackoverflow.com/questions/38491215/programmatically-creating-a-group-cant-access-permissions-from-migration/38491679#38491679
    """
    emit_post_migrate_signal(2, False, "default")

    path = "historical_surveillance/migrations/data/historical_surveillance_school.csv"
    with open(path) as f:
        reader = csv.reader(f)
        for row in reader:
            district = District.objects.get(id=row[8])
            _, created = School.objects.get_or_create(
                id=row[0],
                created_at=row[1],
                created_by=row[2],
                school_code=row[3],
                school_name=row[4],
                category_of_school=row[5],
                updated_at=row[6],
                updated_by=row[7],
                district_name=district,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("historical_surveillance", "0004_populate_districts"),
    ]

    operations = [
        migrations.RunPython(populate_school),
    ]
