# Generated by Django 3.1.7 on 2021-05-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_surveillance', '0004_auto_20210503_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
