# Generated by Django 3.1.7 on 2021-05-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_surveillance', '0004_auto_20210511_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryperformance',
            name='feeding_program',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='primaryperformance',
            name='girls',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='primaryperformance',
            name='primary_enrollment',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='primaryperformance',
            name='repeaters',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='primaryperformance',
            name='teachers',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='primaryperformance',
            name='total_bursaries',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='primaryperformance',
            name='trained_teachers',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
