# Generated by Django 3.1.7 on 2021-05-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historical_surveillance', '0003_merge_20210502_0556'),
        ('historical_surveillance', '0005_auto_20210503_1432'),
        ('historical_surveillance', '0005_auto_20210503_0430'),
    ]

    operations = [
    ]
