# Generated by Django 3.1.7 on 2021-05-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_surveillance', '0006_merge_20210503_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalexpenditure',
            name='educational_expenditure',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nationalexpenditure',
            name='gdp_millions',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nationalexpenditure',
            name='government_expenditure',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nationalexpenditure',
            name='primary_school_expenditure',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nationalexpenditure',
            name='secondary_school_expenditure',
            field=models.FloatField(max_length=50),
        ),
    ]
